# -*- coding: utf-8 -*-
"""Qianchi Huang CS146-Winter2022-PS3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oUr8xCcf0nnamiWgvh2aVoChlz_LbWKy
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch.utils.data import TensorDataset, DataLoader
from PIL import Image

# To add your own Drive Run this cell.
from google.colab import drive
drive.mount('/content/drive')

######################################################################
# OneLayerNetwork
######################################################################

class OneLayerNetwork(torch.nn.Module):
    def __init__(self):
        super(OneLayerNetwork, self).__init__()
        self.oneLayerNetwork = torch.nn.Linear(784, 3)


    def forward(self, x):
        # x.shape = (n_batch, n_features)

        outputs = self.oneLayerNetwork(x)
        return outputs

######################################################################
# TwoLayerNetwork
######################################################################

class TwoLayerNetwork(torch.nn.Module):
    def __init__(self):
        super(TwoLayerNetwork, self).__init__()
        self.twolayerNetwork1 = torch.nn.Linear(784, 400)
        self.twolayerNetwork2 = torch.nn.Linear(400, 3)


    def forward(self, x):
        # x.shape = (n_batch, n_features)

        sigmoid = torch.nn.Sigmoid()
        u = sigmoid(self.twolayerNetwork1(x))
        outputs = self.twolayerNetwork2(u)
        return outputs

# load data from csv
# X.shape = (n_examples, n_features), y.shape = (n_examples, )
def load_data(filename):
    data = np.loadtxt(filename)
    y = data[:, 0].astype(int)
    X = data[:, 1:].astype(np.float32) / 255
    return X, y

# plot one example
# x.shape = (features, )
def plot_img(x):
    x = x.reshape(28, 28)
    img = Image.fromarray(x*255)
    plt.figure()
    plt.imshow(img)
    return

def evaluate_loss(model, criterion, dataloader):
    model.eval()
    total_loss = 0.0
    for batch_X, batch_y in dataloader:
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        total_loss += loss.item()
        
    return total_loss / len(dataloader)

def evaluate_acc(model, dataloader):
    model.eval()
    total_acc = 0.0
    for batch_X, batch_y in dataloader:
        outputs = model(batch_X)
        predictions = torch.argmax(outputs, dim=1)
        total_acc += (predictions==batch_y).sum()
        
    return total_acc / len(dataloader.dataset)

def train(model, criterion, optimizer, train_loader, valid_loader):
    train_loss_list = []
    valid_loss_list = []
    train_acc_list = []
    valid_acc_list = []
    for epoch in range(1, 31):
        model.train()
        for batch_X, batch_y in train_loader:
            y_pred = model.forward(batch_X)
            model.zero_grad()
            loss = criterion(y_pred, batch_y)
            loss.backward()
            optimizer.step()
            
        train_loss = evaluate_loss(model, criterion, train_loader)
        valid_loss = evaluate_loss(model, criterion, valid_loader)
        train_acc = evaluate_acc(model, train_loader)
        valid_acc = evaluate_acc(model, valid_loader)
        train_loss_list.append(train_loss)
        valid_loss_list.append(valid_loss)
        train_acc_list.append(train_acc)
        valid_acc_list.append(valid_acc)

        print(f"| epoch {epoch:2d} | train loss {train_loss:.6f} | train acc {train_acc:.6f} | valid loss {valid_loss:.6f} | valid acc {valid_acc:.6f} |")

    return train_loss_list, valid_loss_list, train_acc_list, valid_acc_list

######################################################################
# main
######################################################################

def main():

    # fix random seed
    np.random.seed(0)
    torch.manual_seed(0)

    # load data with correct file path

    data_directory_path =  "/content/drive/My Drive"


    # X.shape = (n_examples, n_features)
    # y.shape = (n_examples, )
    X_train, y_train = load_data(os.path.join(data_directory_path, "ps3_train.csv"))
    X_valid, y_valid = load_data(os.path.join(data_directory_path, "ps3_valid.csv"))
    X_test, y_test = load_data(os.path.join(data_directory_path, "ps3_test.csv"))
    #print out three training images with different labels
    plot_img(X_train[7])
    plot_img(X_train[23])
    plot_img(X_train[222])


    print("Data preparation...")

    ### convert numpy arrays to tensors
    X_train = torch.from_numpy(X_train)
    X_valid = torch.from_numpy(X_valid)
    X_test = torch.from_numpy(X_test)
    y_train = torch.from_numpy(y_train)
    y_valid = torch.from_numpy(y_valid)
    y_test = torch.from_numpy(y_test)

    ### prepare dataloaders for training, validation, and testing

    train_loader= DataLoader(TensorDataset(X_train, y_train),batch_size = 10)
    valid_loader = DataLoader(TensorDataset(X_valid, y_valid),batch_size = 10)
    test_loader = DataLoader(TensorDataset(X_test, y_test),batch_size = 10)
    

    ### prepare OneLayerNetwork, criterion, and optimizer
    model_one = OneLayerNetwork()
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model_one.parameters(),lr = 0.0005)

    print("Start training OneLayerNetwork...")
    results_one = train(model_one, criterion, optimizer, train_loader, valid_loader)
    print("Done!")

    ### prepare TwoLayerNetwork, criterion, and optimizer
    model_two = TwoLayerNetwork()
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model_two.parameters(),lr = 0.0005)


    print("Start training TwoLayerNetwork...")
    results_two = train(model_two, criterion, optimizer, train_loader, valid_loader)
    print("Done!")

    one_train_loss, one_valid_loss, one_train_acc, one_valid_acc = results_one
    two_train_loss, two_valid_loss, two_train_acc, two_valid_acc = results_two

    ###generate a plot to comare one_train_loss, one_valid_loss, two_train_loss, two_valid_loss
    epoch = np.arange(1 , 31)
    plt.figure()
    plt.plot(epoch, one_train_loss, color='red', label='one layer train loss', marker = 'x')
    plt.plot(epoch, one_valid_loss, color='blue', label='one layer valid loss', marker = 'x')
    plt.plot(epoch, two_train_loss, color='green', label='two layer train loss', marker = 'x')
    plt.plot(epoch, two_valid_loss, color='orange', label='two layer valid loss', marker = 'x')
    plt.ylabel('Loss')
    plt.xlabel('Epochs')
    plt.legend()
    plt.show()

    ### generate a plot to comare one_train_acc, one_valid_acc, two_train_acc, two_valid_acc
    plt.figure()
    plt.plot(epoch, one_train_acc, color='red', label='one layer train acc', marker = 'x')
    plt.plot(epoch, one_valid_acc, color='blue', label='one layer valid acc', marker = 'x')
    plt.plot(epoch, two_train_acc, color='green', label='two layer train acc', marker = 'x')
    plt.plot(epoch, two_valid_acc, color='orange', label='two layer valid acc', marker = 'x')
    plt.ylabel('Accuracy')
    plt.xlabel('Epochs')
    plt.legend()
    plt.show()

    ### calculate the test accuracy
    one_test_acc = evaluate_acc(model_one, test_loader)
    two_test_acc = evaluate_acc(model_two, test_loader)
    print("The test accuracy of the one-layer network is ", one_test_acc)
    print("The test accuracy of the two-layer network is ", two_test_acc)

    ### replace the SGD optimizer with the Adam optimizer and do the experiments again
    model_one = OneLayerNetwork()
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model_one.parameters(),lr = 0.0005)

    print("Start training OneLayerNetwork...")
    results_one = train(model_one, criterion, optimizer, train_loader, valid_loader)
    print("Done!")

    model_two = TwoLayerNetwork()
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model_two.parameters(),lr = 0.0005)


    print("Start training TwoLayerNetwork...")
    results_two = train(model_two, criterion, optimizer, train_loader, valid_loader)
    print("Done!")

    one_train_loss, one_valid_loss, one_train_acc, one_valid_acc = results_one
    two_train_loss, two_valid_loss, two_train_acc, two_valid_acc = results_two

    epoch = np.arange(1 , 31)
    plt.figure()
    plt.plot(epoch, one_train_loss, color='red', label='one layer train loss', marker = 'x')
    plt.plot(epoch, one_valid_loss, color='blue', label='one layer valid loss', marker = 'x')
    plt.plot(epoch, two_train_loss, color='green', label='two layer train loss', marker = 'x')
    plt.plot(epoch, two_valid_loss, color='orange', label='two layer valid loss', marker = 'x')
    plt.ylabel('Loss')
    plt.xlabel('Epochs')
    plt.legend()
    plt.show()

    plt.figure()
    plt.plot(epoch, one_train_acc, color='red', label='one layer train acc', marker = 'x')
    plt.plot(epoch, one_valid_acc, color='blue', label='one layer valid acc', marker = 'x')
    plt.plot(epoch, two_train_acc, color='green', label='two layer train acc', marker = 'x')
    plt.plot(epoch, two_valid_acc, color='orange', label='two layer valid acc', marker = 'x')
    plt.ylabel('Accuracy')
    plt.xlabel('Epochs')
    plt.legend()
    plt.show()
 
    one_test_acc = evaluate_acc(model_one, test_loader)
    two_test_acc = evaluate_acc(model_two, test_loader)
    print("The test accuracy of the one-layer network is ", one_test_acc)
    print("The test accuracy of the two-layer network is ", two_test_acc)




if __name__ == "__main__":
    main()
